// generate.ts: the capability-registry CLI (GH #1807). Composes the registry from disk and writes the one
// committed projection, `site/capability-registry.json`, plus its `site/public/` twin (the sitemap two-copy
// vehicle: Vite hard-errors on a static JS import from publicDir, so the page imports the src-tree copy and
// the public copy serves `fetch`). No timestamp, sorted rows: two runs produce no diff.
//
// It also writes `src/registry/selection-projection.gen.ts` (T-0025, GH #1815 item 3): the `selection.json`
// sidecars alone, as a pure TypeScript module the browser-safe `./registry` subpath carries, so in-page tooling
// reads selection guidance without the `./agent` embed that bundles every prompt. Same loader, same sidecars,
// a derived copy and never a source.
//
//   npm run generate:registry          write the three outputs
//   npm run generate:registry -- --dry compose and print the counts, write nothing
//
// The drift gate (`generate.test.ts`) imports `projectionText` and `selectionProjectionModule` and compares
// them to the committed bytes, so the writer and the gate share one serializer and cannot drift on formatting
// alone. The `main()` call is guarded by the CLI-entry check, so importing this module never writes (the
// GH #112 tools rule).

import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { composeRegistry } from '../../src/registry/compose.ts'
import type { CapabilityRegistry, SelectionProjection } from '../../src/registry/types.ts'
import { loadRegistrySources } from './load.ts'

/** The two committed copies, repo-root-relative. */
export const PROJECTION_PATHS = ['site/capability-registry.json', 'site/public/capability-registry.json'] as const

/** The browser-safe selection projection module, repo-root-relative. */
export const SELECTION_PROJECTION_PATH = 'packages/agent-ui/a2ui/src/registry/selection-projection.gen.ts'

/** The command a stale projection's failure message names. */
export const REGENERATE_COMMAND = 'npm run generate:registry'

/** Compose the registry from the files under `root`. */
export function buildRegistry(root: string): CapabilityRegistry {
  return composeRegistry(loadRegistrySources(root))
}

/** The ONE serialization the writer and the drift gate share. */
export function formatProjection(registry: CapabilityRegistry): string {
  return `${JSON.stringify(registry, null, 2)}\n`
}

/** The projection's exact bytes for the files under `root`. */
export function projectionText(root: string): string {
  return formatProjection(buildRegistry(root))
}

/** The module's first line: it names the writer and the fix, and the freshness gate asserts it. */
export const SELECTION_PROJECTION_HEADER = `// GENERATED by tools/registry/generate.ts. DO NOT EDIT: run ${REGENERATE_COMMAND}`

/** A JS literal for `value`: JSON, with `'`, U+2028 and U+2029 escaped (the `generate-agent-assets.mjs` rule,
 *  so no embedded sidecar text can read as an import specifier to the repo's raw-text scanners). */
function literal(value: unknown): string {
  return JSON.stringify(value).replace(/'/g, '\\u0027').replace(/\u2028/g, '\\u2028').replace(/\u2029/g, '\\u2029')
}

/** One `<scope>: { <type>: <entry>, ... }` block, one type per line, in the sidecar's authored order. */
function scopeBlock(scope: string, guidance: SelectionProjection['base'][string]): string[] {
  return [`    ${literal(scope)}: {`, ...Object.entries(guidance).map(([type, entry]) => `      ${literal(type)}: ${literal(entry)},`), '    },']
}

/** The ONE serialization of the selection projection module, shared by the writer and the drift gate. */
export function formatSelectionProjection(projection: SelectionProjection): string {
  const block = (scopes: SelectionProjection['base']): string[] => Object.entries(scopes).flatMap(([scope, g]) => scopeBlock(scope, g))
  return [
    SELECTION_PROJECTION_HEADER,
    '// Source: every selection.json under packages/agent-ui/a2ui/src/catalog/ (ADR-0232), read by the registry loader.',
    '// Pure data: the `./registry` subpath carries it with no `node:*` and no import from `src/agent/`.',
    "import type { SelectionProjection } from './types.ts'",
    '',
    'export const SELECTION_PROJECTION: SelectionProjection = {',
    '  base: {',
    ...block(projection.base),
    '  },',
    '  persona: {',
    ...block(projection.persona),
    '  },',
    '}',
    '',
  ].join('\n')
}

/** The selection projection module's exact bytes for the sidecars under `root`. */
export function selectionProjectionModule(root: string): string {
  return formatSelectionProjection(loadRegistrySources(root).guidance)
}

function countBy(rows: readonly { readonly kind: string }[]): string {
  const counts = new Map<string, number>()
  for (const r of rows) counts.set(r.kind, (counts.get(r.kind) ?? 0) + 1)
  return [...counts].map(([k, n]) => `${n} ${k}`).join(', ')
}

function main(): void {
  const root = process.cwd()
  const registry = buildRegistry(root)
  const personaRows = Object.values(registry.personas).flat()
  const summary = `base: ${countBy(registry.base)}; personas: ${Object.keys(registry.personas).length} (${personaRows.length} rows)`
  if (process.argv.includes('--dry')) {
    console.log(`registry (dry): ${summary}`)
    return
  }
  const text = formatProjection(registry)
  for (const rel of PROJECTION_PATHS) writeFileSync(join(root, rel), text)
  writeFileSync(join(root, SELECTION_PROJECTION_PATH), selectionProjectionModule(root))
  console.log(`registry: wrote ${PROJECTION_PATHS.length} copies and the selection projection; ${summary}`)
}

if (process.argv[1] !== undefined && process.argv[1].endsWith('registry/generate.ts')) main()
