// GENERATED by scripts/generate-props.mjs from source-list.md — DO NOT EDIT BY HAND (ADR-0173).
// Re-run `node scripts/generate-props.mjs source-list` to regenerate (or with no args to regenerate the whole fleet).
import { type PropsSchema } from '../../dom/index.ts'
import { sourcesProp } from './source-list-model.ts'

export const props = {
  // The source entries — index markers are the array POSITION (1-based), never producer-authored, so marker↔row drift is unrepresentable by construction (ADR-0214 Context fact 1). — generated from source-list.md attributes.sources — edit the descriptor, not this file.
  sources: sourcesProp,
} satisfies PropsSchema
