// GENERATED by scripts/generate-props.mjs from avatar.md — DO NOT EDIT BY HAND (ADR-0173).
// Re-run `node scripts/generate-props.mjs avatar` to regenerate (or with no args to regenerate the whole fleet).
import { prop, type PropsSchema } from '../../dom/index.ts'

export const props = {
  // An image URL for the fallback chain's first link; a load error falls back without ever painting a broken-image box. — generated from avatar.md attributes.src — edit the descriptor, not this file.
  src: prop.string(''),
  // The identity the initials derive from; NOT announced by default (SPEC-R6). — generated from avatar.md attributes.identity — edit the descriptor, not this file.
  identity: prop.string(''),
  // The a11y escape hatch — non-empty makes the avatar itself the accessible name (role=img). — generated from avatar.md attributes.label — edit the descriptor, not this file.
  label: { ...prop.string(''), reflect: true },
  // A step on the compact-realm widget-box ramp (sm, md default, lg). — generated from avatar.md attributes.size — edit the descriptor, not this file.
  size: { ...prop.enum(['sm', 'md', 'lg'] as const, 'md'), reflect: true },
} satisfies PropsSchema
