// site/lib/capability-registry.ts: the Capability Registry page's pure model (GH #1807). The page shows one
// catalog id's composed capability view, from the committed projection `site/capability-registry.json`
// (generated by `npm run generate:registry`, drift-gated in `a2ui/tools/registry/generate.test.ts`). The
// composition is the a2ui package's own `registryViewFor`, never re-derived here; this module only joins the
// two site-owned facts the a2ui package cannot import: `TIER_OF` and `NESTED_ONLY` (a2ui-catalog-tiers.ts).
import { FLEET_CATALOG_ID, registryViewFor } from '@agent-ui/a2ui/registry'
import type { CapabilityRegistry, CapabilityRow } from '@agent-ui/a2ui/registry'
import registryJson from '../capability-registry.json'
import { NESTED_ONLY, TIER_LABEL, TIER_OF } from './a2ui-catalog-tiers.ts'

/** The committed projection, typed. */
export const REGISTRY = registryJson as unknown as CapabilityRegistry

/** Every catalog id the page can show: each base, then each persona derived id for a base it targets. */
export function catalogIds(registry: CapabilityRegistry): string[] {
  // The default catalog leads (the page's initial view), the rest id-sorted.
  const bases = registry.base
    .filter((r) => r.kind === 'catalog')
    .map((r) => r.name!)
    .sort((a, b) => (a === FLEET_CATALOG_ID ? -1 : b === FLEET_CATALOG_ID ? 1 : a < b ? -1 : 1))
  const derived: string[] = []
  for (const [personaId, rows] of Object.entries(registry.personas)) {
    const targets = rows.find((r) => r.kind === 'fragment')?.targetCatalogs ?? []
    for (const base of bases) if (targets.includes(base)) derived.push(`${base}--${personaId}`)
  }
  return [...bases, ...derived.sort()]
}

/** One type line of the page. */
export interface TypeLine {
  readonly name: string
  readonly tag: string
  /** The control's descriptor `tier:` (geometry size class), joined by tag; `''` when the type renders no fleet control. */
  readonly descriptorTier: string
  /** The site's own A2UI Catalog taxonomy tier (`TIER_OF`); `''` for a type outside the default catalog. */
  readonly tier: string
  readonly nestedOnly: boolean
  readonly personaOnly: boolean
  readonly status: string
  readonly use: string
  readonly notFor: string
}

export interface PageModel {
  readonly catalogId: string
  readonly lines: readonly TypeLine[]
  readonly personaOnlyTypes: readonly string[]
  readonly functions: readonly string[]
  readonly retrievable: readonly string[]
}

const statusText = (row: CapabilityRow): string => (row.status.reason === undefined ? row.status.state : `${row.status.state}: ${row.status.reason}`)

/** The page model for one catalog id: the composed view, with the site's tier join page-side. */
export function pageModel(registry: CapabilityRegistry, catalogId: string): PageModel {
  const view = registryViewFor(registry, catalogId)
  const personaOnly = new Set(view.personaOnlyTypes)
  const tierByTag = new Map(registry.base.filter((r) => r.kind === 'control').map((r) => [r.tag!, r.tier ?? ''] as const))
  const lines = view.types.map((row): TypeLine => {
    const name = row.name!
    const tier = Object.hasOwn(TIER_OF, name) ? TIER_LABEL[TIER_OF[name]!] : ''
    return {
      name,
      tag: row.tag ?? '',
      descriptorTier: row.tag === undefined ? '' : (tierByTag.get(row.tag) ?? ''),
      tier,
      nestedOnly: NESTED_ONLY.has(name),
      personaOnly: personaOnly.has(name),
      status: statusText(row),
      use: (row.intents ?? []).join('; '),
      notFor: (row.notFor ?? []).map((e) => `${e.type} (${e.why})`).join(', '),
    }
  })
  return {
    catalogId,
    lines,
    personaOnlyTypes: view.personaOnlyTypes,
    functions: view.functions.map((r) => r.name!),
    retrievable: view.retrievable.map((r) => r.name!),
  }
}
