// selection.ts: the browser-safe resolver over the committed selection projection (T-0025, GH #1815 item 3).
//
// The `selection.json` sidecars (ADR-0232) reach the producer through `src/agent/selection-guidance.ts`, which
// reads them from the build-time embed that also carries every prompt, so an in-page tool (agent-admin, the
// devtools harness page) cannot take them without taking the prompt stack. `selection-projection.gen.ts` is the
// sidecars alone, generated by `npm run generate:registry` from the same loader the registry projection uses
// (a derived copy, never a source: the sidecars stay the one place guidance is authored). This module is the
// pure lookup over it: no `node:*`, no import from `src/agent/`, and the same id rules as the Node resolver
// `selectionGuidanceForId`, held equal by `selection.test.ts`.

import type { GuidanceMap, SelectionProjection } from './types.ts'
import { SELECTION_PROJECTION } from './selection-projection.gen.ts'

const EMPTY: GuidanceMap = {}

/**
 * Resolve a catalog id to its per-type guidance (`intents` and `notFor`, keyed by type id): a base id maps to
 * its own sidecar; a derived `<base>--<persona>` id (split on the FIRST `--`) maps to the base entries plus the
 * persona's (base only when the persona half is unknown, empty when the base half is); any other id, including
 * the inbound-only canonical-URI alias, maps to `{}`. `projection` is the committed one unless a caller plants
 * another (the negative controls do).
 */
export function selectionProjectionFor(catalogId: string, projection: SelectionProjection = SELECTION_PROJECTION): GuidanceMap {
  const sep = catalogId.indexOf('--')
  if (sep === -1) return Object.hasOwn(projection.base, catalogId) ? projection.base[catalogId]! : EMPTY
  const baseId = catalogId.slice(0, sep)
  const personaId = catalogId.slice(sep + 2)
  if (!Object.hasOwn(projection.base, baseId)) return EMPTY
  const base = projection.base[baseId]!
  if (!Object.hasOwn(projection.persona, personaId)) return base
  return { ...base, ...projection.persona[personaId]! }
}
