// GENERATED by scripts/generate-props.mjs from toggle.md — DO NOT EDIT BY HAND (ADR-0173).
// Re-run `node scripts/generate-props.mjs toggle` to regenerate (or with no args to regenerate the whole fleet).
import { prop, type PropsSchema } from '../../dom/index.ts'

export const props = {
  // The toggle's ON/OFF state — mirrors internals.ariaPressed ("true"/"false"). A press flips it ONLY if no `toggle` listener calls preventDefault() first (see Refused toggle below); setting it directly (JS/attribute) always applies immediately, no refusal path. — generated from toggle.md attributes.pressed — edit the descriptor, not this file.
  pressed: { ...prop.boolean(false), reflect: true },
  // Fully inert — no press activation, no key handling, removed from the tab order. — generated from toggle.md attributes.disabled — edit the descriptor, not this file.
  disabled: { ...prop.boolean(false), reflect: true },
  // A step on the Control-band dimensional ramp (sm, md default, lg); an ancestor [scale]/[density] also apply (the button.css ramp, geometry.md). — generated from toggle.md attributes.size — edit the descriptor, not this file.
  size: { ...prop.enum(['sm', 'md', 'lg'] as const, 'md'), reflect: true },
} satisfies PropsSchema
