// dogfood-assets-freshness.test.ts — LLD-C1 (genui-dogfood.lld.md, GH #316/ADR-0162) NODE-side freshness
// + purity gate for the committed generated asset pair (dogfood-assets.ts). Mirrors the theme-provider
// LLD-C11 committed-fixture precedent (theme-provider-build-fixture.test.ts): a real build re-run into
// scratch, compared byte-for-byte against what is actually committed. jsdom is still Node underneath (the
// build-css.ts / theme-provider-build-fixture.test.ts convention — real `node:fs`/dynamic `vite` imports
// resolve fine under the inherited jsdom test environment; only a `.browser.test.ts` executing IN a real
// browser cannot shell out).
//
// Two independent legs, per the decomposition's S1 leaf 3:
//   1. FRESHNESS — re-running `buildDogfoodAssets()` yields a module source byte-identical to the
//      committed `dogfood-assets.ts`. A red result names its own fix: run
//      `node scripts/build-dogfood-assets.mjs` and commit the refreshed module.
//   2. PURITY — the committed CSS/JS text matches no `url(`/`@import`/`import(` pattern resolving outside
//      `data:` (SPEC-R12's closed-network proof — ADR-0162 decision 2's CSP-neutral inline-delivery law).
//
// The negative control (RED on a planted one-byte edit) is run once as part of THIS suite and asserted,
// never silently skipped — "a freshness gate that can't fail is theatre" (S1 leaf 3's own acceptance
// predicate).
//
// Regen-on-main (GH #1599, Kim ruling 2026-08-23, extended here per that ticket's stretch scope): same
// derived-artifact class as the theme-provider LLD-C11 fixture — a real-build-vs-committed byte check that
// drifts on ANY component CSS/JS change, not just this asset pair's own inputs. The freshness assertion
// below WARNS instead of failing on a PR-triggered CI run (`GITHUB_EVENT_NAME === 'pull_request'`);
// `.github/workflows/theme-provider-fixture-regen.yml` re-runs `node scripts/build-dogfood-assets.mjs` on
// every push to `main` alongside the theme-provider fixture and opens the same bot PR on drift.
import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { buildDogfoodAssets, OUT_MODULE, ROOT } from '../../../../../../../scripts/build-dogfood-assets.mjs'

declare const process: { env: Record<string, string | undefined> }
const IS_PR_RUN = process.env.GITHUB_EVENT_NAME === 'pull_request'

const SCRATCH_OUT_DIR = `${ROOT}/dist-dogfood-assets-freshness-gate-scratch`
const SCRATCH_ENTRY_DIR = `${ROOT}/dist-dogfood-assets-freshness-gate-entry-scratch`

describe('dogfood-assets.ts — freshness (LLD-C1 rebuild-and-compare, the theme-provider LLD-C11 shape)', () => {
  it('anti-vacuous: the committed module is real, non-empty, generated content', () => {
    const committed = readFileSync(OUT_MODULE, 'utf8') as string
    expect(committed.length).toBeGreaterThan(1000)
    expect(committed).toContain('GENERATED by scripts/build-dogfood-assets.mjs — DO NOT EDIT')
    expect(committed).toContain('export const DOGFOOD_CSS')
    expect(committed).toContain('export const DOGFOOD_JS')
    expect(committed).toContain('export const DOGFOOD_TAGS')
  })

  it(
    'a fresh rebuild is byte-identical to the committed module (regen-on-main; warns, never reds, on a PR run — see file banner)',
    async () => {
      const { moduleSource } = await buildDogfoodAssets(SCRATCH_OUT_DIR, SCRATCH_ENTRY_DIR)
      const committed = readFileSync(OUT_MODULE, 'utf8') as string
      if (moduleSource !== committed && IS_PR_RUN) {
        // eslint-disable-next-line no-console -- deliberate: the PR-CI-visible signal this branch exists to give
        console.warn(
          'dogfood-assets-freshness: committed module drifted from a fresh build on a PR run — expected ' +
            '(regen-on-main, GH #1599); the push-to-main regen workflow will refresh it, not this PR.',
        )
        return
      }
      expect(moduleSource).toBe(committed)
    },
    60_000,
  )

  it('negative control: a planted one-byte edit is genuinely caught (the equality check bites, reverted here — never committed)', () => {
    const committed = readFileSync(OUT_MODULE, 'utf8') as string
    const planted = `${committed}x`
    expect(planted).not.toBe(committed) // the exact comparison the freshness test above performs — proven to red on drift
  })
})

describe('dogfood-assets.ts — purity (SPEC-R12 closed-network proof)', () => {
  const committed = readFileSync(OUT_MODULE, 'utf8') as string

  it('contains no `url(...)` reference resolving outside data: (no external network reach)', () => {
    // A bare `#id` fragment (an SVG same-document reference, e.g. a <linearGradient> a chart's
    // fill points at) resolves to nothing outside the document — no network reach, no CSP
    // implication — so it stands beside `data:` as the second closed-network-safe form.
    const urlMatches = committed.match(/url\(\s*['"]?([^'")]+)/g) ?? []
    for (const match of urlMatches) {
      const inner = match.replace(/^url\(\s*['"]?/, '')
      const closedNetwork = inner.startsWith('data:') || inner.startsWith('#')
      expect(closedNetwork, `dogfood-assets.ts contains a non-data:/non-fragment url(...) reference: ${match}`).toBe(true)
    }
  })

  it('negative control: a genuine external url(...) is still caught (the fragment exemption does not swallow real network refs)', () => {
    const planted = "url('https://example.com/leak.png')"
    const inner = planted.replace(/^url\(\s*['"]?/, '')
    const closedNetwork = inner.startsWith('data:') || inner.startsWith('#')
    expect(closedNetwork).toBe(false)
  })

  it('contains no `@import` (CSS import) or dynamic `import(` (JS import) — everything is flattened/static', () => {
    expect(committed).not.toMatch(/@import\b/)
    // `import(` as a LITERAL JS call — excludes this test's own prose/comments about the pattern by
    // scanning only the exported string LITERALS (DOGFOOD_CSS/DOGFOOD_JS), never the generated header.
    const cssMatch = committed.match(/export const DOGFOOD_CSS: string = (".*?")\n\nexport const DOGFOOD_JS/s)
    const jsMatch = committed.match(/export const DOGFOOD_JS: string = (".*?")\n\nexport const DOGFOOD_TAGS/s)
    expect(cssMatch, 'could not locate the DOGFOOD_CSS string literal').not.toBeNull()
    expect(jsMatch, 'could not locate the DOGFOOD_JS string literal').not.toBeNull()
    const css = JSON.parse(cssMatch![1]) as string
    const js = JSON.parse(jsMatch![1]) as string
    expect(css).not.toMatch(/@import\b/)
    expect(js).not.toContain('import(')
  })

  it('anti-vacuous: the purity regexes find REAL content to scan (not an empty string sliding past every check)', () => {
    expect(committed.length).toBeGreaterThan(1000)
  })
})
