// GENERATED by scripts/generate-props.mjs from disclosure.md — DO NOT EDIT BY HAND (ADR-0173).
// Re-run `node scripts/generate-props.mjs disclosure` to regenerate (or with no args to regenerate the whole fleet).
import { prop, type PropsSchema } from '../../dom/index.ts'

export const props = {
  // generated from disclosure.md attributes.open — edit the descriptor, not this file.
  open: { ...prop.boolean(false), reflect: true },
  // generated from disclosure.md attributes.summary — edit the descriptor, not this file.
  summary: { ...prop.string(''), reflect: true },
  // Opt-in contained chrome (GH #1283) — body padding + a surface background with corners on the shared fleet radius. Absent (the default), the fold is a simple UNPADDED component with no background or border chrome. — generated from disclosure.md attributes.contained — edit the descriptor, not this file.
  contained: { ...prop.boolean(false), reflect: true },
} satisfies PropsSchema
