// GENERATED by scripts/generate-props.mjs from progress.md — DO NOT EDIT BY HAND (ADR-0173).
// Re-run `node scripts/generate-props.mjs progress` to regenerate (or with no args to regenerate the whole fleet).
import { prop, type PropsSchema } from '../../dom/index.ts'

export const props = {
  // null (default) ⇒ indeterminate — the native progress semantic, no separate boolean to desync. — generated from progress.md attributes.current — edit the descriptor, not this file.
  current: prop.number(null),
  // The ARIA progressbar default (100) — percent-natural for {current:42} with zero extra props. — generated from progress.md attributes.max — edit the descriptor, not this file.
  max: prop.number(100),
  // The accessible name (SPEC-R3); empty ⇒ no internals.ariaLabel. — generated from progress.md attributes.label — edit the descriptor, not this file.
  label: { ...prop.string(''), reflect: true },
  // SPEC-R1 Amendment v1 (GH #614) — null/non-finite/<2/fractional/malformed ⇒ continuous mode, unchanged. A finite integer ≥2 activates discrete "step N of M" mode — effectiveMax=segments (max ignored), effectiveValue floors to an integer. — generated from progress.md attributes.segments — edit the descriptor, not this file.
  segments: prop.number(null),
} satisfies PropsSchema
