// generate-controls.ts: the control registry, the demo-only `all` entry and the per-control exports (ADR-0233).
//
// One pure implementation serves the `scripts/generate-controls.mjs` CLI that writes the artifacts and the
// `controls/controls-gen-driftwire.test.ts` gate that regenerates them in memory and compares (the
// generate-props.mjs / generate-props.ts pairing, reused). No `node:*` import here: callers pass readers.
//
// Outputs, all derived from the fleet (every `controls/{folder}/{name}.md` outside `_` folders):
//   - `src/controls/registry.gen.ts`: `CONTROLS`, one lazy `ControlRecord` per tag, sorted by tag, a record
//     carrying its descriptor's `defines:` sub-element tags when it declares any;
//   - `src/all.gen.ts`: DEMO-ONLY, one bare import per control entry module, sorted by path;
//   - `src/all.gen.css`: DEMO-ONLY, the seam sheet, then one import per control sheet, sorted by path;
//   - the generator-owned `exports` keys of the components `package.json`: `./controls/{name}` and
//     `./controls/{name}.css` per control, plus `./registry`, `./all` and `./all.css`. Every other key is
//     hand-owned and kept as it is.

import { parseDescriptor, scalarSeq, splitFrontmatter } from './component-descriptor.ts'
import { descriptorPath, type ControlsReader, type FleetEntry } from './control-graph.ts'

/**
 * One fleet control as the generator sees it: its tag, folder, file name, declared `uses` tags and declared
 * `defines` tags (the sub-element tags its entry module self-defines besides its own; absent means none).
 */
export interface ControlsGenEntry {
  readonly tag: string
  readonly folder: string
  readonly name: string
  readonly uses: readonly string[]
  readonly defines?: readonly string[]
}

/** The generated artifacts: three file texts and the generator-owned `exports` keys (sorted). */
export interface GeneratedControls {
  readonly registry: string
  readonly allTs: string
  readonly allCss: string
  readonly exports: Record<string, string>
}

/** Where each generated file lives, relative to the components package root. */
export const GENERATED_FILES = {
  registry: 'src/controls/registry.gen.ts',
  allTs: 'src/all.gen.ts',
  allCss: 'src/all.gen.css',
} as const

/** The three generator-owned keys that are not per-control. */
const FIXED_KEYS: Readonly<Record<string, string>> = {
  './registry': `./${GENERATED_FILES.registry}`,
  './all': `./${GENERATED_FILES.allTs}`,
  './all.css': `./${GENERATED_FILES.allCss}`,
}

/** Plain code-unit order, the order `Array.prototype.sort` gives strings. */
const byString = (a: string, b: string): number => (a < b ? -1 : a > b ? 1 : 0)

// Quoted apart from the keyword, so an import-statement scanner (`layering.test.ts`) never reads the text
// this module writes as an import of its own.
const quote = (spec: string): string => `'${spec}'`
const bareImport = (spec: string): string => `import ${quote(spec)}`
const cssImport = (spec: string): string => `@import ${quote(spec)};`

const REGISTRY_HEADER = [
  '// registry.gen.ts: GENERATED by scripts/generate-controls.mjs from the fleet descriptors (ADR-0233).',
  '// Never hand-edit; regenerate with `node scripts/generate-controls.mjs` from the repo root.',
  '// Drift gate: src/controls/controls-gen-driftwire.test.ts.',
  '//',
  '// One lazy record per fleet tag, sorted by tag: `load()` imports the entry module, which self-defines the',
  '// tag; `css` is the sheet relative to `src/controls/`; `uses` is the descriptor `uses:` block; `defines`, present',
  '// only on a family entry, is its descriptor `defines:` block: the sub-element tags that entry module also',
  '// self-defines on import, which have no record of their own.',
]

const ALL_TS_HEADER = [
  '// all.gen.ts: GENERATED by scripts/generate-controls.mjs from the fleet descriptors (ADR-0233).',
  '// Never hand-edit; regenerate with `node scripts/generate-controls.mjs` from the repo root.',
  '//',
  '// DEMO-ONLY: imports every fleet control entry module for its self-define side effect, sorted by path, and',
  '// exports nothing. Package code never imports it (gate: src/controls/all-purity.test.ts); an app imports',
  '// the controls it uses, one `./controls/{name}` subpath each.',
]

const ALL_CSS_HEADER = [
  '/* all.gen.css: GENERATED by scripts/generate-controls.mjs from the fleet descriptors (ADR-0233).',
  ' * Never hand-edit; regenerate with `node scripts/generate-controls.mjs` from the repo root.',
  ' *',
  ' * DEMO-ONLY: the seam sheet (`shared-styles.css`) once, then every fleet control sheet, sorted by path.',
  ' * Control sheets are order-free (each is self-scoped and imports the sheets of its `uses`), proven on both',
  ' * engines by src/controls/css-order.browser.test.ts. An app links the foundation, the seam sheet and',
  ' * only the control sheets it uses.',
  ' */',
]

/**
 * Throw when two entries share a tag or an export name (`./controls/{name}` would collide), or when a
 * `defines` tag is a fleet tag or is declared by two entries (a sub-element has exactly one parent).
 */
function assertUnique(entries: readonly ControlsGenEntry[]): void {
  const tags = new Set<string>()
  const names = new Set<string>()
  for (const e of entries) {
    if (tags.has(e.tag)) throw new Error(`generate-controls: duplicate tag ${e.tag}`)
    if (names.has(e.name)) throw new Error(`generate-controls: duplicate control name ${e.name} (./controls/${e.name})`)
    tags.add(e.tag)
    names.add(e.name)
  }
  const declared = new Map<string, string>()
  for (const e of entries) {
    for (const sub of e.defines ?? []) {
      if (tags.has(sub)) throw new Error(`generate-controls: ${e.tag} defines ${sub}, which is a fleet control with its own record`)
      const other = declared.get(sub)
      if (other !== undefined) throw new Error(`generate-controls: ${sub} is defined by both ${other} and ${e.tag}`)
      declared.set(sub, e.tag)
    }
  }
}

/** One registry line: `'ui-x': { tag, load, css, uses },`, plus `defines: [...]` when the entry declares any. */
function registryLine(e: ControlsGenEntry): string {
  const uses = [...e.uses].sort(byString).map(quote).join(', ')
  const defines = [...(e.defines ?? [])].sort(byString).map(quote).join(', ')
  const load = `() => import(${quote(`./${e.folder}/${e.name}.ts`)})`
  const tail = defines === '' ? '' : `, defines: [${defines}]`
  return `  ${quote(e.tag)}: { tag: ${quote(e.tag)}, load: ${load}, css: ${quote(`./${e.folder}/${e.name}.css`)}, uses: [${uses}]${tail} },`
}

/**
 * Generate the registry, the demo-only `all` pair and the generator-owned `exports` keys from the fleet.
 * Pure and deterministic: the same entries in any order give byte-identical output. Throws on a duplicate
 * tag or control name, and on a `defines` tag that is a fleet tag or has two parents.
 */
export function generateControls(entries: readonly ControlsGenEntry[]): GeneratedControls {
  assertUnique(entries)
  const byTag = [...entries].sort((a, b) => byString(a.tag, b.tag))
  const tsPaths = entries.map((e) => `./controls/${e.folder}/${e.name}.ts`).sort(byString)
  const cssPaths = entries.map((e) => `./controls/${e.folder}/${e.name}.css`).sort(byString)

  const registry = [
    ...REGISTRY_HEADER,
    '',
    `import type { ControlRecord } from ${quote('./control-record.ts')}`,
    '',
    'export type { ControlRecord }',
    '',
    '/** Every fleet control, keyed by tag (ADR-0233). */',
    'export const CONTROLS: Readonly<Record<string, ControlRecord>> = {',
    ...byTag.map(registryLine),
    '}',
    '',
  ].join('\n')

  const allTs = [...ALL_TS_HEADER, '', ...tsPaths.map(bareImport), ''].join('\n')

  const allCss = [...ALL_CSS_HEADER, cssImport('./shared-styles.css'), ...cssPaths.map(cssImport), ''].join('\n')

  const exportsOut: Record<string, string> = { ...FIXED_KEYS }
  for (const e of entries) {
    exportsOut[`./controls/${e.name}`] = `./src/controls/${e.folder}/${e.name}.ts`
    exportsOut[`./controls/${e.name}.css`] = `./src/controls/${e.folder}/${e.name}.css`
  }
  const exports: Record<string, string> = {}
  for (const key of Object.keys(exportsOut).sort(byString)) exports[key] = exportsOut[key]

  return { registry, allTs, allCss, exports }
}

/** True for a key the generator owns: every `./controls/*` key, plus `./registry`, `./all` and `./all.css`. */
export const isGeneratorOwnedKey = (key: string): boolean => key.startsWith('./controls/') || key in FIXED_KEYS

/**
 * The `exports` map with the generator-owned keys replaced by `generated` (a stale `./controls/*` key is
 * dropped), every hand-owned key kept with its value, and all keys in plain sorted order.
 */
export function mergeExports(current: Readonly<Record<string, unknown>>, generated: Readonly<Record<string, string>>): Record<string, unknown> {
  const merged: Record<string, unknown> = {}
  for (const [key, value] of Object.entries(current)) if (!isGeneratorOwnedKey(key)) merged[key] = value
  for (const [key, value] of Object.entries(generated)) merged[key] = value
  const out: Record<string, unknown> = {}
  for (const key of Object.keys(merged).sort(byString)) out[key] = merged[key]
  return out
}

/**
 * `packageJsonText` with its `exports` map merged (`mergeExports`) and every other field kept in place,
 * written as two-space JSON plus a trailing newline.
 */
export function withGeneratedExports(packageJsonText: string, generated: Readonly<Record<string, string>>): string {
  const pkg = JSON.parse(packageJsonText) as Record<string, unknown>
  const current = (pkg['exports'] ?? {}) as Record<string, unknown>
  pkg['exports'] = mergeExports(current, generated)
  return `${JSON.stringify(pkg, null, 2)}\n`
}

/**
 * The generator entries for a fleet (from `fleetFromDescriptors`): each control's `uses` and optional
 * `defines` read from its descriptor with the descriptor parser. Throws when a descriptor cannot be read or
 * declares no `uses` block (sync it first with `node scripts/codemod-uses.mjs`).
 */
export function controlsGenEntries(fleet: readonly FleetEntry[], read: ControlsReader): ControlsGenEntry[] {
  return fleet.map((entry) => {
    const rel = descriptorPath(entry)
    const source = read(rel)
    if (source === undefined) throw new Error(`generate-controls: cannot read descriptor ${rel}`)
    const desc = parseDescriptor(splitFrontmatter(source).fence)
    if (!desc.sequences.has('uses')) throw new Error(`generate-controls: ${rel} declares no uses block; run node scripts/codemod-uses.mjs`)
    return { tag: entry.tag, folder: entry.folder, name: entry.name, uses: scalarSeq(desc, 'uses'), defines: scalarSeq(desc, 'defines') }
  })
}

/** Reads a file by its path relative to the components package root; `undefined` when it does not exist. */
export type PackageReader = (packageRelPath: string) => string | undefined

/**
 * The package-relative paths of every stale generated artifact: each of the three files whose text differs
 * from `generated` (or is missing), and `package.json` when its generator-owned `exports` keys or key order
 * differ. Empty when everything is in sync.
 */
export function staleControlsArtifacts(read: PackageReader, generated: GeneratedControls): string[] {
  const stale: string[] = []
  const files: [string, string][] = [
    [GENERATED_FILES.registry, generated.registry],
    [GENERATED_FILES.allTs, generated.allTs],
    [GENERATED_FILES.allCss, generated.allCss],
  ]
  for (const [path, text] of files) if (read(path) !== text) stale.push(path)
  const pkgText = read('package.json')
  if (pkgText === undefined || withGeneratedExports(pkgText, generated.exports) !== pkgText) stale.push('package.json')
  return stale
}
