// GENERATED by scripts/generate-props.mjs from audio.md — DO NOT EDIT BY HAND (ADR-0173).
// Re-run `node scripts/generate-props.mjs audio` to regenerate (or with no args to regenerate the whole fleet).
import { prop, type PropsSchema } from '../../dom/index.ts'

export const props = {
  // The audio URL. Renders no <audio> at all when empty (never a dead player bar). — generated from audio.md attributes.src — edit the descriptor, not this file.
  src: prop.string(''),
  // REQUIRED in spirit (the a2ui catalog enforces it at admission, the Image `alt` discipline) — written as the interior <audio>'s aria-label, its accessible name. Never synthesized. — generated from audio.md attributes.label — edit the descriptor, not this file.
  label: prop.string(''),
  // The native <audio preload> policy — metadata (default), none, or auto. Autoplay/loop are deliberately ABSENT at v1 (the ui-video fence, verbatim). — generated from audio.md attributes.preload — edit the descriptor, not this file.
  preload: prop.enum(['none', 'metadata', 'auto'] as const, 'metadata'),
} satisfies PropsSchema
