// GENERATED by scripts/generate-props.mjs from image.md — DO NOT EDIT BY HAND (ADR-0173).
// Re-run `node scripts/generate-props.mjs image` to regenerate (or with no args to regenerate the whole fleet).
import { prop, type PropsSchema } from '../../dom/index.ts'

export const props = {
  // The image URL. Renders no <img> at all when empty (never a broken-image box). — generated from image.md attributes.src — edit the descriptor, not this file.
  src: prop.string(''),
  // REQUIRED in spirit (the a2ui catalog enforces it at admission; this component never coerces or hides an empty value) — the interior <img>'s accessible name. Never synthesized, never defaulted to decorative empty-alt (contrast with ui-avatar's own interior-node empty-alt posture, which is a DIFFERENT contract for a DIFFERENT component: avatar's img is one link in a decorative-by-default fallback chain; ui-image's img IS the content). — generated from image.md attributes.alt — edit the descriptor, not this file.
  alt: prop.string(''),
  // The interior <img>'s object-fit — cover (default, fills and crops) or contain (letterboxes, preserves the whole frame). — generated from image.md attributes.fit — edit the descriptor, not this file.
  fit: { ...prop.enum(['cover', 'contain'] as const, 'cover'), reflect: true },
  // A "W/H" aspect ratio (e.g. "16/9", "1/1", "4/3") driving the host CSS aspect-ratio box. Malformed/omitted falls back to 16/9 — NEVER to "auto" — so space is reserved before the image loads regardless of its natural dimensions (zero CLS, by construction). — generated from image.md attributes.aspect — edit the descriptor, not this file.
  aspect: prop.string('16/9'),
  // A hint affecting loading defaults (image-model.ts usageHintDefaults) — hero is the likely LCP element (loading=eager, fetchpriority=high); thumb/avatar/inline (the default) all lazy-load (loading=lazy, decoding=async) — zero-dep, native, no IntersectionObserver. — generated from image.md attributes.usageHint — edit the descriptor, not this file.
  usageHint: { ...prop.enum(['hero', 'thumb', 'avatar', 'inline'] as const, 'inline'), attribute: 'usage-hint' },
} satisfies PropsSchema
