// GENERATED by scripts/generate-props.mjs from table.md — DO NOT EDIT BY HAND (ADR-0173).
// Re-run `node scripts/generate-props.mjs table` to regenerate (or with no args to regenerate the whole fleet).
import { prop, type PropsSchema } from '../../dom/index.ts'
import { tableColumnsProp, tableFilterProp, tableRowsProp, tableSelectedProp, tableSortProp } from './table-model.ts'

export const props = {
  // Typed column definitions — sortable/searchable opt columns into the per-column capabilities. — generated from table.md attributes.columns — edit the descriptor, not this file.
  columns: tableColumnsProp,
  // The record rows, open objects keyed by each column's key. — generated from table.md attributes.rows — edit the descriptor, not this file.
  rows: tableRowsProp,
  // The rendered caption text — the table's accessible name (SPEC-R2/R6). — generated from table.md attributes.label — edit the descriptor, not this file.
  label: { ...prop.string(''), reflect: true },
  // Off by default (no selection column); multi adds a checkbox column + select-all; single adds a radio column. — generated from table.md attributes.selectable — edit the descriptor, not this file.
  selectable: { ...prop.enum(['', 'single', 'multi'] as const, ''), reflect: true },
  // Names the column whose cell values identify rows for selected (cl.4); absent ⇒ the row's data-order index. — generated from table.md attributes.rowKey — edit the descriptor, not this file.
  rowKey: { ...prop.string(''), attribute: 'row-key' },
  // Bindable row identities — commits via select, never by a programmatic write (the fleet commit law). — generated from table.md attributes.selected — edit the descriptor, not this file.
  selected: tableSelectedProp,
  // The current sort column/direction, or null; commits via change (cycles ascending → descending). — generated from table.md attributes.sort — edit the descriptor, not this file.
  sort: tableSortProp,
  // A free-text filter over the rendered cell text of every searchable column ("search what you see"). — generated from table.md attributes.search — edit the descriptor, not this file.
  search: prop.string(''),
  // The bounded facet filter — a row survives when every entry's raw cell value matches one of its values. — generated from table.md attributes.filter — edit the descriptor, not this file.
  filter: tableFilterProp,
  // pageSize > 0 stamps a composed ui-pagination footer and windows the rendered set; 0 (default) is off. — generated from table.md attributes.pageSize — edit the descriptor, not this file.
  pageSize: { ...prop.number(0), attribute: 'page-size' },
  // The 1-based current page; bindable, commits via change (forwarded from the internal ui-pagination). — generated from table.md attributes.page — edit the descriptor, not this file.
  page: prop.number(1),
} satisfies PropsSchema
