// GENERATED by scripts/generate-props.mjs from badge.md — DO NOT EDIT BY HAND (ADR-0173).
// Re-run `node scripts/generate-props.mjs badge` to regenerate (or with no args to regenerate the whole fleet).
import { prop, type PropsSchema } from '../../dom/index.ts'

export const INTENTS = ['neutral', 'info', 'success', 'warning', 'danger'] as const

export const props = {
  // The rendered text — mirrors into the label span; the host's accessible name. — generated from badge.md attributes.label — edit the descriptor, not this file.
  label: { ...prop.string(''), reflect: true },
  // Bindable status data — an out-of-enum runtime write is hardened back to neutral (SPEC-R11 AC2). — generated from badge.md attributes.intent — edit the descriptor, not this file.
  intent: { ...prop.enum(INTENTS, 'neutral'), reflect: true },
} satisfies PropsSchema
