// agent-assets-freshness.test.ts: the committed `assets.gen.ts` and `dogfood-fleet.gen.ts` equal what
// scripts/generate-agent-assets.mjs produces from the tree today, byte for byte. A hard red on every run,
// pull requests included (Kim's ruling): a red names its own fix, `node scripts/generate-agent-assets.mjs`.
//
// The negative controls run in memory, never by mutating the tree: each plants one change in the
// discovered input and asserts the regenerated source differs from the committed one, so the equality
// above cannot pass vacuously.

import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import {
  discoverAgentAssets,
  generateAgentAssetsModules,
  OUT_ASSETS,
  OUT_FLEET,
  readControlFolders,
} from '../../../../../scripts/generate-agent-assets.mjs'
import { deriveDogfoodFleet } from './dogfood-descriptor.ts'

declare const process: { cwd(): string }

type Discovered = ReturnType<typeof discoverAgentAssets>

const generate = generateAgentAssetsModules
const discovered = discoverAgentAssets()
const committedAssets = readFileSync(`${process.cwd()}/${OUT_ASSETS}`, 'utf8') as string
const committedFleet = readFileSync(`${process.cwd()}/${OUT_FLEET}`, 'utf8') as string
const HEADER = '// GENERATED by scripts/generate-agent-assets.mjs. DO NOT EDIT: run node scripts/generate-agent-assets.mjs'
const FIX = 'stale generated agent asset module: run node scripts/generate-agent-assets.mjs and commit the result'

/** `discovered` with one byte appended to the content at `path`. */
function withAppended(path: string): Discovered {
  expect(discovered.text.some((a) => a.path === path), `fixture path ${path} is discovered`).toBe(true)
  return { ...discovered, text: discovered.text.map((a) => (a.path === path ? { path, content: `${a.content}x` } : a)) }
}

describe('generated agent asset modules: freshness', () => {
  it('anti-vacuous: both committed files carry the GENERATED header', () => {
    expect(committedAssets.split('\n')[0]).toBe(HEADER)
    expect(committedFleet.split('\n')[0]).toBe(HEADER)
  })

  it('assets.gen.ts equals the regenerated source byte for byte', () => {
    expect(generate(discovered).assets, FIX).toBe(committedAssets)
  })

  it('dogfood-fleet.gen.ts equals the regenerated source byte for byte', () => {
    expect(generate(discovered).fleet, FIX).toBe(committedFleet)
  })
})

describe('generated agent asset modules: negative controls (in memory)', () => {
  it('one byte appended to agent/prompts/honesty-floor.md makes assets.gen.ts stale', () => {
    expect(generate(withAppended('agent/prompts/honesty-floor.md')).assets).not.toBe(committedAssets)
  })

  it('one byte appended to a selection.json makes assets.gen.ts stale', () => {
    const sidecar = discovered.text.find((a) => a.path.endsWith('/selection.json'))
    expect(sidecar).toBeDefined()
    expect(generate(withAppended(sidecar!.path)).assets).not.toBe(committedAssets)
  })

  it('a changed first body sentence in the button descriptor makes dogfood-fleet.gen.ts stale', () => {
    const folders = readControlFolders()
    const isButton = (md: string): boolean => /^tag:\s*ui-button\s*$/m.test(md)
    const button = folders.find((f) => f.descriptors.some(isButton))
    expect(button, 'the button folder is discovered').toBeDefined()
    let changed = false
    const planted = folders.map((f) =>
      f !== button
        ? f
        : {
            ...f,
            descriptors: f.descriptors.map((md) => {
              if (!isButton(md)) return md
              // The body opens with the `# ui-button` heading line; the next line starts the first sentence.
              const next = md.replace(/(\n---\n\s*#[^\n]*\n+)/, '$1Planted negative-control sentence. ')
              changed = next !== md
              return next
            }),
          },
    )
    expect(changed, 'the planted sentence landed in the button descriptor').toBe(true)
    const regenerated = generate({ ...discovered, fleet: deriveDogfoodFleet(planted) }).fleet
    expect(regenerated).not.toBe(committedFleet)
    expect(regenerated).toContain('Planted negative-control sentence.')
  })
})
