// asset-source.ts: read access to the embedded `./agent` file assets (`assets.gen.ts`, generated by
// scripts/generate-agent-assets.mjs). Keys are POSIX paths relative to packages/agent-ui/a2ui/src/, for
// example `agent/prompts/grammar.md` or `catalog/personas/concierge/selection.json`.
//
// Fail loud, never silent: an unknown key throws `AgentAssetError` naming the regen command, the same rule
// the Worker fs shim applies to a path it does not carry. Deliberately not re-exported from `index.ts`.

import { AGENT_ASSETS } from './assets.gen.ts'

const REGEN = 'node scripts/generate-agent-assets.mjs'

/** A key that names no embedded asset (or a directory key with nothing under it). */
export class AgentAssetError extends Error {
  constructor(message: string) {
    super(message)
    this.name = 'AgentAssetError'
  }
}

/** The embedded text of `key`. Throws `AgentAssetError` when no asset carries that key. */
export function readAsset(key: string): string {
  if (Object.hasOwn(AGENT_ASSETS, key)) return AGENT_ASSETS[key]!
  throw new AgentAssetError(`agent asset "${key}" is not embedded; if the file exists, run ${REGEN}`)
}

/** The unique first path segments of every key under `dirKey + '/'`, in default sort order (the
 *  `readdirSync(...).sort()` order the fs loaders use). Throws `AgentAssetError` when no key lies under
 *  `dirKey`. */
export function listAssets(dirKey: string): string[] {
  const prefix = `${dirKey}/`
  const names = new Set<string>()
  for (const key of Object.keys(AGENT_ASSETS)) {
    if (key.startsWith(prefix)) names.add(key.slice(prefix.length).split('/')[0]!)
  }
  if (names.size === 0) throw new AgentAssetError(`no agent asset is embedded under "${dirKey}/"; if the directory exists, run ${REGEN}`)
  return [...names].sort()
}
