// site/pages/capability-registry.ts: the CAPABILITY REGISTRY (GH #1807), one catalog id's composed view.
//
// A derived index, never a source (ADR-0173 cl.5): every row comes from `site/capability-registry.json`,
// generated by `npm run generate:registry` from the descriptors, catalogs, selection sidecars, persona
// fragments, mini-skills and corpus shards. Selecting a persona (`agent-ui--croupier`) lists the base catalog's
// types plus the persona fragment's, with the same `use:` and `not for:` guidance the prompt inventory carries;
// the tier column is the site's own A2UI Catalog taxonomy, joined here because the a2ui package cannot import it.
import { mountPage, pageLead } from './_page.ts' // FIRST: foundation CSS cascade + self-defining ui-* controls
import { exampleSection, el } from '../lib/specimens.ts'
import { tableHead, tableRow, textCell, codeCell } from '../lib/doc-page.ts'
import { REGISTRY, catalogIds, pageModel } from '../lib/capability-registry.ts'
import type { UISelectElement } from '@agent-ui/components/controls/select'

const IDS = catalogIds(REGISTRY)
if (IDS.length === 0) throw new Error('capability-registry: the committed projection lists no catalog (run npm run generate:registry)')

const { content } = mountPage({
  title: 'Capability Registry',
  intro:
    'One queryable index of what an agent can emit: every catalog type with the control it renders, its tier, its ' +
    'selection guidance, and which types a persona adds. Generated, never hand-edited: npm run generate:registry.',
})
content.append(
  pageLead(
    'Pick a catalog id. A base id lists that catalog. A derived id (base--persona) lists the base types plus the ' +
      'persona fragment’s own types, marked persona-only.',
  ),
)

const field = document.createElement('ui-field')
field.setAttribute('label', 'Catalog id')
const select = document.createElement('ui-select') as UISelectElement
select.className = 'registry-select'
// A doc page ships no stylesheet of its own (doc-page.ts `specimenRow`): inline layout keeps the site bundle's
// CSS, and with it the committed theme-provider built-output fixture, untouched.
select.style.cssText = 'display:grid; inline-size:min(100%, 28rem);'
for (const id of IDS) {
  const option = document.createElement('div')
  option.setAttribute('role', 'option')
  option.setAttribute('value', id)
  option.textContent = id
  select.append(option)
}
field.append(select)
content.append(field)

const out = document.createElement('div')
out.className = 'registry-view'
out.setAttribute('aria-live', 'polite')
content.append(out)

function render(catalogId: string): void {
  const model = pageModel(REGISTRY, catalogId)
  const table = document.createElement('table')
  table.id = 'registry-types-table'
  table.style.cssText = 'inline-size:100%; border-collapse:collapse;'
  const body = document.createElement('tbody')
  for (const line of model.lines) {
    const row = tableRow(
      codeCell(line.name),
      codeCell(line.tag === '' ? 'none' : line.tag),
      textCell(line.descriptorTier === '' ? 'n/a' : line.descriptorTier),
      textCell(line.tier === '' ? 'n/a' : line.tier),
      textCell(line.personaOnly ? `persona-only, ${line.status}` : line.status),
      textCell(line.use === '' ? 'no guidance' : line.use),
      textCell(line.notFor === '' ? '' : line.notFor),
    )
    row.dataset.type = line.name
    if (line.personaOnly) {
      row.dataset.personaOnly = ''
      row.style.fontWeight = '600'
    }
    body.append(row)
  }
  table.append(tableHead('Type', 'Control', 'Descriptor tier', 'Catalog tier', 'Status', 'Use', 'Not for'), body)

  const summary = el('p', {}, [
    document.createTextNode(
      `${model.lines.length} types (${model.personaOnlyTypes.length} persona-only), ${model.functions.length} functions, ` +
        `${model.retrievable.length} mini-skills and corpus shards retrievable under this exact id.`,
    ),
  ])
  out.replaceChildren(exampleSection(`Types of ${catalogId}`, summary, table))
}

select.addEventListener('change', () => render(select.value))
select.value = IDS[0]!
render(IDS[0]!)
