// site/pages/icon-demo.ts — the ui-icon demo (the ratified display-tier `demo`, GH #1279 batch): the REAL
// Phosphor-backed icon leaf in the contexts it actually ships in — leading/trailing button adornments (the
// slot × data-role anatomy), an icon-only button with a `label`-less decorative icon + host aria-label, a
// meaningful standalone icon (`label` ⇒ role=img via internals), an attachment list with file-type glyphs,
// the ambient font-size ramp (the ONE size lever — no [size] attribute exists), and the ink-inherits law
// (color plumbing-free intent tinting). Pairs with the descriptor-derived API doc, site/pages/icon-doc.ts
// (the full ICON_NAMES gallery lives THERE). ui-icon emits no events, so there is no event log.
import { mountPage } from './_page.ts' // FIRST: foundation CSS cascade + self-defining ui-* controls (ADR-0003) — also activates the Phosphor pack
import './containers.css' // shared demo chrome (section spacing + .demo-figure/.demo-caption)
import { captioned, el, exampleSection } from '../lib/specimens.ts'

const { content } = mountPage({
  title: 'ui-icon — demo',
  intro:
    'The icon leaf where it lives: inside buttons (leading / trailing / icon-only), beside list rows, sized by ' +
    'ambient font-size and inked by the surrounding color — never by per-icon plumbing. Every glyph is the ' +
    'REAL Phosphor pack resolved through the @agent-ui/icons adapter. The API table is on the ui-icon API page.',
})

const text = (s: string): Text => document.createTextNode(s)

/** icon — a decorative <ui-icon glyph> (no label ⇒ aria-hidden), optionally slotted into a control's cell. */
function icon(glyph: string, attrs: Record<string, string> = {}): HTMLElement {
  return el('ui-icon', { glyph, ...attrs })
}

/** iconButton — a real ui-button with a leading/trailing icon adornment (slot = POSITION, data-role = CONTENT). */
function iconButton(label: string, glyph: string, slot: 'leading' | 'trailing', variant = 'soft'): HTMLElement {
  return el('ui-button', { variant }, slot === 'leading'
    ? [icon(glyph, { slot, 'data-role': 'icon' }), text(label)]
    : [text(label), icon(glyph, { slot, 'data-role': 'icon' })])
}

// ── buttons — the composer / toolbar row a chat surface actually renders ───────────────────────────────────
const buttonRow = el('ui-row', { gap: 'sm', align: 'center', wrap: '' }, [
  iconButton('Attach file', 'paperclip', 'leading'),
  iconButton('Send', 'paper-plane-right', 'trailing', 'solid'),
  iconButton('Download PDF', 'download-simple', 'leading'),
  iconButton('Next step', 'arrow-right', 'trailing'),
  el('ui-button', { variant: 'ghost', 'icon-only': '', 'aria-label': 'More actions' }, [
    icon('dots-three', { slot: 'leading', 'data-role': 'icon' }),
  ]),
  el('ui-button', { variant: 'ghost', 'icon-only': '', 'aria-label': 'Close' }, [
    icon('x', { slot: 'leading', 'data-role': 'icon' }),
  ]),
])

const buttonNote = el('p', {}, [
  text('Slot names the POSITION ('), el('code', {}, [text('slot="leading|trailing"')]),
  text('), '), el('code', {}, [text('data-role="icon"')]),
  text(' names the CONTENT so the button sizes the cell to its icon ramp. Icons beside a visible label stay decorative (no '),
  el('code', {}, [text('label')]), text('); an icon-only button names itself through the host '),
  el('code', {}, [text('aria-label')]), text(' — the icon never carries the name twice.'),
])

// ── an attachment list — file-type glyphs beside realistic rows ───────────────────────────────────────────
const files: readonly [glyph: string, name: string, meta: string][] = [
  ['file-pdf', 'Q3-board-deck.pdf', '4.2 MB · uploaded 09:14'],
  ['file-image', 'venue-floorplan.png', '812 KB · uploaded 09:15'],
  ['file-code', 'catering-order.json', '3 KB · generated by the agent'],
  ['file-zip', 'brand-assets-2026.zip', '38 MB · shared link'],
  ['file-audio', 'kickoff-recording.m4a', '52:10 · transcript ready'],
]
const fileList = el('ui-list', { gap: 'xs' }, files.map(([glyph, name, meta]) =>
  el('ui-row', { gap: 'sm', align: 'center' }, [
    icon(glyph),
    el('ui-column', { gap: 'none' }, [
      el('ui-text', { variant: 'body' }, [text(name)]),
      el('ui-text', { variant: 'label', size: 'sm' }, [text(meta)]),
    ]),
  ]),
))
fileList.style.fontSize = '1.25rem' // the rows' ambient font-size IS the icon size lever (see the ramp below)

// ── the size ramp — ambient font-size only; there is no [size] attribute by design ────────────────────────
const ramp = el('ui-row', { gap: 'lg', align: 'baseline' }, ['0.875rem', '1rem', '1.5rem', '2rem', '3rem'].map((size) => {
  const glyph = icon('calendar-check')
  glyph.style.fontSize = size
  return captioned(`font-size: ${size}`, glyph)
}))

const rampNote = el('p', {}, [
  text('The host is a '), el('code', {}, [text('1em × 1em')]),
  text(' cell (`--md-sys-icon-size`) — the consumer’s ambient font-size, or an explicit inline-size on the host, is the ONLY size lever. No ramp, no `[size]` attribute (geometry.md "intrinsic structural sizing").'),
])

// ── a meaningful icon — `label` ⇒ role=img + aria-label via ElementInternals ─────────────────────────────
const statusRow = el('ui-row', { gap: 'md', align: 'center' }, [
  icon('check-circle', { label: 'Deployed', style: 'color: var(--md-sys-color-primary); font-size: 1.5rem;' }),
  icon('warning', { label: 'Needs attention', style: 'color: var(--md-sys-color-tertiary); font-size: 1.5rem;' }),
  icon('x-circle', { label: 'Failed', style: 'color: var(--md-sys-color-error); font-size: 1.5rem;' }),
  icon('clock', { label: 'Scheduled', style: 'color: var(--md-sys-color-on-surface-variant); font-size: 1.5rem;' }),
])

const statusNote = el('p', {}, [
  text('A non-empty '), el('code', {}, [text('label')]),
  text(' makes an icon MEANINGFUL: role=img + the label as its accessible name, set through ElementInternals (never a host attribute). ' +
    'The ink is `color: inherit` — the injected `<svg fill="currentColor">` tracks whatever the context resolves to, so an intent tint is one CSS `color` on the host, no per-icon plumbing. ' +
    'Shape stays distinct per status (ADR-0057) — hue is never the only channel.'),
])

content.append(
  exampleSection('Inside buttons', buttonRow, buttonNote),
  exampleSection('Beside list rows', fileList),
  exampleSection('Sizing — the ambient font-size ramp', ramp, rampNote),
  exampleSection('Meaningful icons + ink inheritance', statusRow, statusNote),
)
