// generate-agent-assets.test.mjs: the generator's emitted format and CLI (`scripts` vitest project, node).
//   (a) a hostile fixture round-trips byte-exact through plain Node type stripping in a spawned child;
//   (b) two runs over one input are byte-identical, keys sorted;
//   (c) the publish specifier rewrite leaves both emitted sources unchanged, and neither holds a column-0
//       call line or any column-0 line beyond the header, the import type, the export and the close;
//   (d) the CLI, spawned in a scratch fixture root, writes both files and `--check` bites one appended byte.

import { describe, it, expect, afterAll } from 'vitest'
import { execFileSync, spawnSync } from 'node:child_process'
import { appendFileSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { pathToFileURL } from 'node:url'
import { discoverAgentAssets, generateAgentAssetsModules, OUT_ASSETS, OUT_FLEET } from './generate-agent-assets.mjs'
import { rewriteSpecifiers } from './publish/publish-packages.mjs'

const SCRIPT = join(process.cwd(), 'scripts/generate-agent-assets.mjs')
const HEADER = '// GENERATED by scripts/generate-agent-assets.mjs. DO NOT EDIT: run node scripts/generate-agent-assets.mjs'

// A backtick, `${`, a single quote, CRLF, U+2028, U+2029 and an import-specifier lookalike.
const HOSTILE = "a `tick` ${x} it's\r\nnext\u2028line\u2029para; import x from '@agent-ui/components'\nfoo('bar')"

const scratch = []
const tempDir = () => {
  const dir = mkdtempSync(join(tmpdir(), 'generate-agent-assets-'))
  scratch.push(dir)
  return dir
}
afterAll(() => {
  for (const dir of scratch) rmSync(dir, { recursive: true, force: true })
})

const fixtureDiscovered = () => ({
  text: [
    { path: 'catalog/x/selection.json', content: `{"X":{"intents":["${HOSTILE.replace(/[\r\n\u2028\u2029"]/g, ' ')}"]}}\n` },
    { path: 'agent/prompts/hostile.md', content: HOSTILE },
  ],
  fleet: [{ tag: 'ui-hostile', summary: HOSTILE, attrs: "kind: enum(''|a)", siblings: ['ui-hostile-part'] }],
})

// The side-effects.test.mjs column-0 call rule, verbatim.
const TOP_LEVEL_CALL = /^(void |await )?[A-Za-z_$][\w$.]*\(/m

/** Every column-0 line must be one of the five allowed shapes. */
function strayColumnZeroLines(src) {
  return src
    .split('\n')
    .filter((l) => l !== '' && !/^\s/.test(l))
    .filter(
      (l) =>
        !l.startsWith('// ') &&
        !l.startsWith('import type ') &&
        !l.startsWith('export const ') &&
        l !== '})' &&
        l !== ']',
    )
}

describe('(a) round trip through plain Node type stripping', () => {
  it('a hostile fixture reads back byte-exact from a spawned child', () => {
    const discovered = fixtureDiscovered()
    const { assets, fleet } = generateAgentAssetsModules(discovered)
    const dir = tempDir()
    writeFileSync(join(dir, 'assets.mts'), assets)
    writeFileSync(join(dir, 'fleet.mts'), fleet)
    const code = [
      `const a = await import(${JSON.stringify(pathToFileURL(join(dir, 'assets.mts')).href)})`,
      `const f = await import(${JSON.stringify(pathToFileURL(join(dir, 'fleet.mts')).href)})`,
      'process.stdout.write(JSON.stringify({ assets: a.AGENT_ASSETS, fleet: f.DOGFOOD_FLEET, frozen: Object.isFrozen(a.AGENT_ASSETS) }))',
    ].join('\n')
    const out = JSON.parse(execFileSync(process.execPath, ['--input-type=module', '-e', code], { encoding: 'utf8' }))
    expect(out.frozen).toBe(true)
    expect(out.assets).toEqual(Object.fromEntries(discovered.text.map((t) => [t.path, t.content])))
    expect(out.assets['agent/prompts/hostile.md']).toBe(HOSTILE)
    expect(out.fleet).toEqual(discovered.fleet)
    expect(out.fleet[0].summary).toBe(HOSTILE)
  })
})

describe('(b) deterministic', () => {
  it('two runs over one input are byte-identical, and input order does not matter', () => {
    const discovered = fixtureDiscovered()
    const first = generateAgentAssetsModules(discovered)
    const second = generateAgentAssetsModules(discovered)
    const reversed = generateAgentAssetsModules({ ...discovered, text: [...discovered.text].reverse() })
    expect(second).toEqual(first)
    expect(reversed).toEqual(first)
  })

  it('keys are emitted in default sort order (real tree)', () => {
    const { assets } = generateAgentAssetsModules(discoverAgentAssets())
    const keys = assets
      .split('\n')
      .filter((l) => l.startsWith('  "'))
      .map((l) => JSON.parse(l.slice(2, l.indexOf('": ') + 1)))
    expect(keys.length).toBeGreaterThan(30)
    expect(keys).toEqual([...keys].sort())
  })
})

describe('(c) invisible to the raw-text scanners', () => {
  const sources = () => {
    const real = generateAgentAssetsModules(discoverAgentAssets())
    const fixture = generateAgentAssetsModules(fixtureDiscovered())
    return [
      ['real assets', real.assets],
      ['real fleet', real.fleet],
      ['fixture assets', fixture.assets],
      ['fixture fleet', fixture.fleet],
    ]
  }

  it('both emitted sources carry the GENERATED header on line 1', () => {
    for (const [, src] of sources()) expect(src.split('\n')[0]).toBe(HEADER)
  })

  it('rewriteSpecifiers leaves both emitted sources unchanged', () => {
    for (const [name, src] of sources()) expect(rewriteSpecifiers(src, false), name).toBe(src)
  })

  it('neither holds a column-0 call line nor any stray column-0 line', () => {
    for (const [name, src] of sources()) {
      expect(TOP_LEVEL_CALL.test(src), name).toBe(false)
      expect(strayColumnZeroLines(src), name).toEqual([])
    }
  })

  it('anti-vacuous: the column-0 rule bites an unescaped line separator before a call', () => {
    expect(TOP_LEVEL_CALL.test('  "x": "a\u2028foo(",')).toBe(true)
    expect(rewriteSpecifiers("import x from '@agent-ui/components'", false)).not.toBe("import x from '@agent-ui/components'")
  })
})

describe('(d) CLI in a fixture root', () => {
  it('writes both files, --check passes, then bites one appended prompt byte without writing', () => {
    const root = tempDir()
    const prompt = join(root, 'packages/agent-ui/a2ui/src/agent/prompts/fixture.md')
    const sidecar = join(root, 'packages/agent-ui/a2ui/src/catalog/fixture/selection.json')
    const control = join(root, 'packages/agent-ui/components/src/controls/widget')
    mkdirSync(join(root, 'packages/agent-ui/a2ui/src/agent/prompts'), { recursive: true })
    mkdirSync(join(root, 'packages/agent-ui/a2ui/src/catalog/fixture'), { recursive: true })
    mkdirSync(control, { recursive: true })
    writeFileSync(prompt, '# Fixture prompt\n')
    writeFileSync(sidecar, '{"Widget":{"intents":["fixture"],"notFor":[]}}\n')
    writeFileSync(
      join(control, 'widget.md'),
      '---\ntag: ui-widget\nattributes:\n  - name: size\n    type: enum\n    values: [sm, md]\n---\n\n# ui-widget\n\n`ui-widget` is the fixture control.\n',
    )
    writeFileSync(join(control, 'widget.ts'), "customElements.define('ui-widget', class {})\ncustomElements.define('ui-widget-part', class {})\n")

    const run = (...args) => spawnSync(process.execPath, [SCRIPT, ...args], { cwd: root, encoding: 'utf8' })
    const write = run()
    expect(write.status, write.stderr).toBe(0)
    const assets = readFileSync(join(root, OUT_ASSETS), 'utf8')
    const fleet = readFileSync(join(root, OUT_FLEET), 'utf8')
    expect(assets).toContain('"agent/prompts/fixture.md": "# Fixture prompt\\n",')
    expect(assets).toContain('"catalog/fixture/selection.json"')
    expect(fleet).toContain('"tag":"ui-widget"')
    expect(fleet).toContain('"siblings":["ui-widget-part"]')

    const fresh = run('--check')
    expect(fresh.status, fresh.stderr).toBe(0)

    appendFileSync(prompt, 'x')
    const stale = run('--check')
    expect(stale.status).toBe(1)
    expect(stale.stderr).toContain('assets.gen.ts')
    expect(stale.stderr).toContain('node scripts/generate-agent-assets.mjs')
    expect(readFileSync(join(root, OUT_ASSETS), 'utf8')).toBe(assets)
    expect(readFileSync(join(root, OUT_FLEET), 'utf8')).toBe(fleet)
  })
})
