// GENERATED by scripts/generate-props.mjs from video.md — DO NOT EDIT BY HAND (ADR-0173).
// Re-run `node scripts/generate-props.mjs video` to regenerate (or with no args to regenerate the whole fleet).
import { prop, type PropsSchema } from '../../dom/index.ts'

export const props = {
  // The video URL. Renders no <video> at all when empty (never a dead player shell). — generated from video.md attributes.src — edit the descriptor, not this file.
  src: prop.string(''),
  // REQUIRED in spirit (the a2ui catalog enforces it at admission, the Image `alt` discipline) — written as the interior <video>'s aria-label, its accessible name. Never synthesized. — generated from video.md attributes.label — edit the descriptor, not this file.
  label: prop.string(''),
  // Optional poster-frame URL shown before playback starts (the native <video poster> attribute, passed through verbatim; empty ⇒ no poster attribute at all). — generated from video.md attributes.poster — edit the descriptor, not this file.
  poster: prop.string(''),
  // A "W/H" aspect ratio driving the host CSS aspect-ratio box. Malformed/omitted falls back to 16/9 — NEVER to "auto" — so space is reserved before any metadata loads (zero CLS, by construction; the ui-image law). — generated from video.md attributes.aspect — edit the descriptor, not this file.
  aspect: prop.string('16/9'),
  // The native <video preload> policy — metadata (default; dimensions/duration only), none, or auto. Autoplay/loop/muted are deliberately ABSENT at v1 (agent-driven autoplay is a UX hazard — a named future intake, never a silent default). — generated from video.md attributes.preload — edit the descriptor, not this file.
  preload: prop.enum(['none', 'metadata', 'auto'] as const, 'metadata'),
} satisfies PropsSchema
