// GENERATED by scripts/generate-props.mjs from button.md — DO NOT EDIT BY HAND (ADR-0173).
// Re-run `node scripts/generate-props.mjs button` to regenerate (or with no args to regenerate the whole fleet).
import { prop, type PropsSchema } from '../../dom/index.ts'

export const props = {
  // The colour channel — solid (filled, default), soft (tonal), ghost (text-only). — generated from button.md attributes.variant — edit the descriptor, not this file.
  variant: { ...prop.enum(['solid', 'soft', 'ghost'] as const, 'solid'), reflect: true },
  // A step on the dimensional ramp (sm, md default, lg); an ancestor [scale]/[density] also apply. — generated from button.md attributes.size — edit the descriptor, not this file.
  size: { ...prop.enum(['sm', 'md', 'lg'] as const, 'md'), reflect: true },
  // Fully inert — no activation, no key handling, removed from the tab order. — generated from button.md attributes.disabled — edit the descriptor, not this file.
  disabled: { ...prop.boolean(false), reflect: true },
  // Explicit opt-in for a real slotted adornment with NO label content; the accessible name must then come from aria-label (see Slots & roles below). — generated from button.md attributes.iconOnly — edit the descriptor, not this file.
  iconOnly: { ...prop.boolean(false), reflect: true, attribute: 'icon-only' },
  // The ONE sizing opt-out (ADR-0223) — inline-level display + hug posture (the pre-wave shrink-to-content rendering). Absent, the button fills its block container; the R3(a) squareness floor survives both states. — generated from button.md attributes.inline — edit the descriptor, not this file.
  inline: { ...prop.boolean(false), reflect: true },
} satisfies PropsSchema
